### PR TITLE
Migration Guide

### PR DESCRIPTION
**Pull request by AndriiMoskvin**
Migration guide for users how are moving from OneMobileSDK to VerizonVideoPartnerSDK

### CODE REVIEW

**Comment by balavor** [comment]
I'd prefer to have only `README.md` file that will only have the info that we've migrated to VVP SDK and the migration guide. We already have all tutorials, details, examples and so on in our main SDK repo, so we don't need all of those things here.

It will be much easier for those who will open this repo to find out that `OneMobileSDK -> VerizonVideoPartnerSDK` and to see how to migrate instead of searching for that `Migration Guide` file.
@MarkGerl @AndriiMoskvin WDYT?

**Comment by AndriiMoskvin** [comment]
@RomanTysiachnik Agree - added this as first line of Readme.md.

**Review by balavor — DISMISSED** [review]
It is good as for me, but if everyone agreed, we should move the migration guide in readme entirely and drop tutorials. At least, because it is a duplication of what we have in SDK repo.

**Comment by MarkGerl** [comment]
We're going to make this repo read-only anyway -- I don't think we need to hack out tutorials and such.

**Comment by MarkGerl** [comment]
I've added my changes.  @AndriiMoskvin please re-review.

**Review by MarkGerl — CHANGES_REQUESTED** [review]
I've added my changes. @AndriiMoskvin please re-review.

Please don't merge the #README.md file yet.  Wait for me to finish mucking with it.

**Comment by AndriiMoskvin** [comment]
@MarkGerl Updated with correct link to releases.

**Review by MarkGerl — APPROVED** [review]

**Comment by MarkGerl** [comment]
@AndriiMoskvin delete branch?

**Pull request merged**
