### PR TITLE
Fixed build error on tvOS

### PR DESCRIPTION
**Pull request by balavor**
@aol-public/mobile-sdk-team Ready for review

### CODE REVIEW

**Comment by AndriiMoskvin** [comment]
I assume it is not a crash - just a compile error?

**Comment by balavor** [comment]
Yeap

**Comment by AndriiMoskvin** [comment]
Why the PR named as crash...?

**Comment by balavor** [comment]
@AndriiMoskvin not anymore =)

**Review by AndriiMoskvin — APPROVED** [review]

**Pull request merged**
